apiVersion: v1
kind: ConfigMap
metadata:
  name: quelyos-config
  namespace: quelyos
data:
  # PostgreSQL
  POSTGRES_USER: "quelyos"
  POSTGRES_DB: "quelyos"

  # Services URLs (internal)
  BACKEND_URL: "http://backend-service:8069"
  POSTGRES_HOST: "postgres-service"
  REDIS_HOST: "redis-service"

  # App Config
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
