apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitrine-quelyos
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitrine-client
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-client
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
